### ISSUE TITLE
Add more test cases

### ISSUE THREAD

**Issue by hiromimie** [hiromimie/test-private-repo-2#3]
## Overview
We need to add more test cases to improve our test coverage.

## Tasks
- [ ] Add unit tests for main function
- [ ] Add error handling tests
- [ ] Add edge case tests

## Acceptance Criteria
- All tests should be documented
- Test coverage should be above 80%
